# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LineLengthCalc
                                 A QGIS plugin
 Calculate the length of a line
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-08-25
        copyright            : (C) 2022 by Tum
        email                : tum@mail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LineLengthCalc class from file LineLengthCalc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .line_length_calc import LineLengthCalc
    return LineLengthCalc(iface)
